FROM prom/prometheus:latest

# Copier la configuration
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Exposer le port
EXPOSE 9090

# Commande de démarrage
CMD ["--config.file=/etc/prometheus/prometheus.yml", "--web.listen-address=:9090", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/etc/prometheus/console_libraries", "--web.console.templates=/etc/prometheus/consoles"]
